/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	safelist: [
		"from-normal",
		"to-normal",
		"from-fire",
		"to-fire",
		"from-water",
		"to-water",
		"from-grass",
		"to-grass",
		"from-electric",
		"to-electric",
		"from-ice",
		"to-ice",
		"from-fighting",
		"to-fighting",
		"from-poison",
		"to-poison",
		"from-ground",
		"to-ground",
		"from-flying",
		"to-flying",
		"from-psychic",
		"to-psychic",
		"from-bug",
		"to-bug",
		"from-rock",
		"to-rock",
		"from-ghost",
		"to-ghost",
		"from-dragon",
		"to-dragon",
		"from-dark",
		"to-dark",
		"from-steel",
		"to-steel",
		"from-fairy",
		"to-fairy",
	],
	theme: {
		extend: {
			boxShadow: {
				"inset-border": "inset 0 0 10px 2px rgba(0, 0, 0, 0.5)",
			},
			colors: {
				normal: {
					DEFAULT: "#A8A77A",
					light: "#C2C29A",
					dark: "#8F8F5A",
				},
				fire: {
					DEFAULT: "#EE8130",
					light: "#F4A25A",
					dark: "#CC6A29",
				},
				water: {
					DEFAULT: "#6390F0",
					light: "#85A7F5",
					dark: "#5073C9",
				},
				grass: {
					DEFAULT: "#7AC74C",
					light: "#97D56D",
					dark: "#5EA03E",
				},
				electric: {
					DEFAULT: "#F7D02C",
					light: "#F9DF5B",
					dark: "#D4B324",
				},
				ice: {
					DEFAULT: "#96D9D6",
					light: "#B1E4E1",
					dark: "#78B3B0",
				},
				fighting: {
					DEFAULT: "#C22E28",
					light: "#D6524C",
					dark: "#9F2420",
				},
				poison: {
					DEFAULT: "#A33EA1",
					light: "#BB64B9",
					dark: "#832F80",
				},
				ground: {
					DEFAULT: "#E2BF65",
					light: "#EBD494",
					dark: "#BFA651",
				},
				flying: {
					DEFAULT: "#A98FF3",
					light: "#C0A8F5",
					dark: "#8572CC",
				},
				psychic: {
					DEFAULT: "#F95587",
					light: "#FA789F",
					dark: "#D03D6B",
				},
				bug: {
					DEFAULT: "#A6B91A",
					light: "#C0D34A",
					dark: "#879314",
				},
				rock: {
					DEFAULT: "#B6A136",
					light: "#CEBB57",
					dark: "#938128",
				},
				ghost: {
					DEFAULT: "#735797",
					light: "#8F73B0",
					dark: "#5A4275",
				},
				dragon: {
					DEFAULT: "#6F35FC",
					light: "#8E63FF",
					dark: "#5629CB",
				},
				dark: {
					DEFAULT: "#705746",
					light: "#8C7260",
					dark: "#594636",
				},
				steel: {
					DEFAULT: "#B7B7CE",
					light: "#CECEE1",
					dark: "#9292A6",
				},
				fairy: {
					DEFAULT: "#D685AD",
					light: "#E5A5C2",
					dark: "#B56A8D",
				},
			},
		},
	},
	plugins: [],
};
