export const suffixesToRemove = [
	"-own-tempo",
	"-midnight",
	"-starter",
	"-original",
	"-standard",
	"-zen",
	"-alola",
	"-galar",
	"-totem-alola",
	"-vmax",
	"-mega-x",
	"-mega-y",
	"-mega",
	"-gmax",
	"-terastal",
	"-stellar",
	"-ice",
	"-shadow",
	"-paldea-combat-breed",
	"-paldea-blaze-breed",
	"-paldea-aqua-breed",
	"-hisui",
	"-totem",
	"-battle-bond",
	"-primal",
	"-sky",
	"-land",
	"-complete",
	"-10",
	"-50",
	"-origin",
	"-incarnate",
	"-therian",
	"-crowned",
	"-eternamax",
	"-single-strike",
	"-rapid-strike",
	"-black",
	"-white",
	"-ordinary",
	"-resolute",
	"-aria",
	"-pirouette",
	"-dawn",
	"-midday",
	"-dusk",
	"-dada",
	"-bloodmoon",
	"-male",
	"-female",
	"-sunny",
	"-rainy",
	"-snowy",
	"-normal",
	"-attack",
	"-defense",
	"-speed",
	"-altered",
	"-wellspring-mask",
	"-hearthflame-mask",
	"-cornerstone-mask",
	"-ultra",
	"-solo",
	"-school",
];

export function formatName(name) {
	suffixesToRemove.forEach((suffix) => {
		name = name.replace(suffix, "");
	});

	name = name.includes("-") ? name.replace(/-/g, " ") : name;

	name = name.includes("_") ? name.replace(/_/g, " ") : name;

	return name;
}
